import React, { useState, useEffect } from 'react';
import { Search, Calendar, Clock, FileText, Download, CheckCircle2, AlertCircle, RefreshCw, Send, ArrowLeft, User, Users } from 'lucide-react';

interface Session {
  id: str;
  title: str;
  start_time: number;
  end_time?: number;
  duration_seconds: number;
  has_mom: boolean;
  mom?: any;
}

const API_BASE = 'http://localhost:8765/api';

export const SessionHistory: React.FC = () => {
  const [sessions, setSessions] = useState<Session[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedSessionId, setSelectedSessionId] = useState<string | null>(null);
  const [selectedSessionDetail, setSelectedSessionDetail] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [retriggerStatus, setRetriggerStatus] = useState<string | null>(null);

  const fetchSessions = async (query: string = '') => {
    setIsLoading(true);
    try {
      const res = await fetch(`${API_BASE}/sessions?query=${encodeURIComponent(query)}`);
      if (res.ok) {
        const data = await res.json();
        setSessions(data);
      }
    } catch (err) {
      console.error('[Fetch Sessions Error]', err);
    }
    setIsLoading(false);
  };

  useEffect(() => {
    fetchSessions();
  }, []);

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    fetchSessions(searchQuery);
  };

  const handleSelectSession = async (sid: string) => {
    setSelectedSessionId(sid);
    try {
      const res = await fetch(`${API_BASE}/sessions/${sid}`);
      if (res.ok) {
        const data = await res.json();
        setSelectedSessionDetail(data);
      }
    } catch (err) {
      console.error('[Session Detail Error]', err);
    }
  };

  const handleRetriggerWebhook = async (webhookId: string = 'mock-webhook-1') => {
    if (!selectedSessionId) return;
    setRetriggerStatus('Retriggering webhook...');
    try {
      const res = await fetch(`${API_BASE}/webhooks/retrigger`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ webhook_id: webhookId, session_id: selectedSessionId })
      });
      if (res.ok) {
        const data = await res.json();
        setRetriggerStatus(`Success! Status Code: ${data.status_code}`);
        setTimeout(() => setRetriggerStatus(null), 4000);
      }
    } catch (err) {
      setRetriggerStatus('Failed to deliver webhook.');
    }
  };

  const exportMarkdown = () => {
    if (!selectedSessionDetail || !selectedSessionDetail.mom) return;
    const mom = selectedSessionDetail.mom;
    const md = `# Minutes of Meeting: ${selectedSessionId}
Generated by Adrishyaa-Local (Offline AI Co-Pilot)

## Executive Summary
${mom.executive_summary}

## Key Topics Discussed
${mom.key_topics.map((t: string) => `- ${t}`).join('\n')}

## Decisions Made
${mom.decisions_made.map((d: string) => `- ${d}`).join('\n')}

## Action Items
${mom.action_items.map((a: any) => `- **${a.task}** (Assignee: ${a.assignee}, Deadline: ${a.deadline})`).join('\n')}

## Unresolved Questions
${mom.unresolved_questions.map((q: string) => `- ${q}`).join('\n')}
`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MoM-${selectedSessionId}.md`;
    a.click();
  };

  return (
    <div className="flex flex-col h-[calc(100vh-140px)] gap-4">
      {/* Search Header */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 glass-card rounded-xl p-4 border border-slate-800">
        <div>
          <h2 className="font-semibold text-lg text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-400" />
            <span>Session History & Local RAG Search</span>
          </h2>
          <p className="text-xs text-slate-400">Search across past meeting transcripts, structured MoMs, and action items locally.</p>
        </div>

        <form onSubmit={handleSearchSubmit} className="relative w-full sm:w-80">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search transcripts or topics..."
            className="w-full bg-slate-900 text-white placeholder-slate-500 rounded-lg pl-9 pr-20 py-2 text-xs border border-slate-700 focus:outline-none focus:border-indigo-500"
          />
          <button
            type="submit"
            className="absolute right-1 top-1 bg-indigo-600 hover:bg-indigo-500 text-white px-2.5 py-1 rounded text-xs transition-colors"
          >
            Search
          </button>
        </form>
      </div>

      {/* Main Content: Split List and Detail View */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 overflow-hidden">
        {/* Sessions List (1 Col) */}
        <div className="glass-card rounded-2xl p-4 border border-slate-800 flex flex-col overflow-hidden">
          <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Past Meetings</h3>
          <div className="flex-1 overflow-y-auto space-y-2.5 pr-1">
            {sessions.length === 0 ? (
              <div className="text-center py-10 text-slate-500 text-xs">
                No past meeting sessions found.
              </div>
            ) : (
              sessions.map((s) => (
                <div
                  key={s.id}
                  onClick={() => handleSelectSession(s.id)}
                  className={`p-3.5 rounded-xl border cursor-pointer transition-all ${
                    selectedSessionId === s.id
                      ? 'bg-indigo-950/60 border-indigo-500/50 shadow-md'
                      : 'bg-slate-900/60 border-slate-800 hover:bg-slate-800/60'
                  }`}
                >
                  <div className="flex items-center justify-between gap-2 mb-1">
                    <span className="font-semibold text-sm text-white truncate">{s.title}</span>
                    {s.has_mom && (
                      <span className="bg-emerald-950 text-emerald-300 border border-emerald-500/30 text-[10px] px-1.5 py-0.5 rounded font-mono">
                        MoM Ready
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-3 text-[11px] text-slate-400">
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3 h-3 text-slate-500" />
                      {new Date(s.start_time * 1000).toLocaleDateString()}
                    </span>
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3 text-slate-500" />
                      {Math.floor(s.duration_seconds / 60)} mins
                    </span>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Selected Session Detail View (2 Cols) */}
        <div className="lg:col-span-2 glass-card rounded-2xl p-5 border border-slate-800 flex flex-col overflow-hidden">
          {!selectedSessionDetail ? (
            <div className="h-full flex flex-col items-center justify-center text-slate-500 text-center py-12">
              <FileText className="w-10 h-10 text-slate-600 mb-2" />
              <p className="text-sm font-medium text-slate-400">Select a meeting session to view details</p>
              <p className="text-xs text-slate-600 mt-0.5">Review structured MoMs, action items, and complete transcripts.</p>
            </div>
          ) : (
            <div className="flex-1 overflow-y-auto space-y-5 pr-2">
              {/* Detail Header & Export buttons */}
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 pb-4 border-b border-slate-800">
                <div>
                  <h3 className="font-semibold text-lg text-white">{selectedSessionId}</h3>
                  <p className="text-xs text-slate-400 mt-0.5">Archived Session Minutes of Meeting</p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleRetriggerWebhook('mock-webhook-1')}
                    className="bg-indigo-950 hover:bg-indigo-900 text-indigo-300 border border-indigo-500/40 text-xs px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-colors"
                  >
                    <Send className="w-3.5 h-3.5 text-indigo-400" />
                    <span>Re-trigger Webhook</span>
                  </button>
                  <button
                    onClick={exportMarkdown}
                    className="bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Export MD</span>
                  </button>
                </div>
              </div>

              {retriggerStatus && (
                <div className="bg-indigo-950/80 border border-indigo-500/40 text-indigo-200 text-xs p-2.5 rounded-lg animate-in fade-in">
                  {retriggerStatus}
                </div>
              )}

              {/* Structured MoM Section */}
              {selectedSessionDetail.mom ? (
                <div className="space-y-4">
                  {/* Executive Summary */}
                  <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4">
                    <h4 className="text-xs font-semibold text-indigo-400 uppercase tracking-wider mb-1.5">
                      Executive Summary
                    </h4>
                    <p className="text-slate-200 text-sm leading-relaxed">
                      {selectedSessionDetail.mom.executive_summary}
                    </p>
                  </div>

                  {/* Key Topics & Decisions */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4">
                      <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">
                        Key Topics Discussed
                      </h4>
                      <ul className="space-y-1.5 text-xs text-slate-300">
                        {selectedSessionDetail.mom.key_topics.map((t: string, i: number) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-indigo-400">•</span>
                            <span>{t}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4">
                      <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">
                        Decisions Made
                      </h4>
                      <ul className="space-y-1.5 text-xs text-slate-300">
                        {selectedSessionDetail.mom.decisions_made.map((d: string, i: number) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-emerald-400">✓</span>
                            <span>{d}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Action Items */}
                  <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4">
                    <h4 className="text-xs font-semibold text-indigo-400 uppercase tracking-wider mb-3">
                      Action Items
                    </h4>
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs border-collapse">
                        <thead>
                          <tr className="border-b border-slate-800 text-slate-400">
                            <th className="py-2 px-2">Task</th>
                            <th className="py-2 px-2">Assignee</th>
                            <th className="py-2 px-2">Deadline</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-800/60 text-slate-200">
                          {selectedSessionDetail.mom.action_items.map((item: any, idx: number) => (
                            <tr key={idx} className="hover:bg-slate-800/40">
                              <td className="py-2.5 px-2 font-medium">{item.task}</td>
                              <td className="py-2.5 px-2">
                                <span className="bg-indigo-950 text-indigo-300 border border-indigo-500/30 px-2 py-0.5 rounded text-[11px]">
                                  {item.assignee}
                                </span>
                              </td>
                              <td className="py-2.5 px-2 text-slate-400">{item.deadline}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-4 text-xs text-slate-400">
                  MoM processing is pending or session was ended before completion.
                </div>
              )}

              {/* Full Transcript Section */}
              <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4 mt-4">
                <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
                  Full Session Transcript
                </h4>
                <div className="space-y-2 max-h-60 overflow-y-auto pr-2">
                  {selectedSessionDetail.transcripts.map((item: any, idx: number) => (
                    <div key={idx} className="text-xs flex items-start gap-2">
                      <span className="font-semibold text-indigo-400 shrink-0">{item.speaker}:</span>
                      <span className="text-slate-300">{item.text}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
